pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Stair-Rover
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.CreativeSynergyZ.com/
#
# 2. URL of this page
url:              http://creativesynergyz.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           A re-imagined highschool senior portrait experience
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://kck.st/12bbLkw
  #
  # URL of a cover photo of your project
  cover_image:    http://static.wixstatic.com/media/b11e60_7416a5fc41a5d30b8b458bbe6c23b90f.jpg
  #
  # Use a one-liner to describe your project
  description:    Help us bring this to the graduation class of 2014
#
# 4. Your Twitter handle
twitter_handle:   csynergyz
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  Hi:) Hope you are having an awesome day! <br />
  you are here because we know you have influence, when you share people listen. <br />
  Our kickstarter project is now live and we need your support,
  so please shart some syneryz love â™¥
